<?php
/**
 * AdGroupServiceConversionOptimizer
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AdGroupServiceConversionOptimizer Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt; AdGroupServiceConversionOptimizerは、コンバージョン最適化制御を保持するオブジェクトです。&lt;br&gt; このフィールドは省略可能となります。その際、ADD時のoptimizerTypeのデフォルト設定値はNONEとなります。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; AdGroupServiceConversionOptimizer retains conversion optimization control.&lt;br&gt; This field is optional. The default value of optimizerType in ADD operation will be NONE. &lt;/div&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdGroupServiceConversionOptimizer implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AdGroupServiceConversionOptimizer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'auto_conversion_optimizer' => '\OpenAPI\Client\Model\AdGroupServiceAutoConversionOptimizer',
        'manual_conversion_optimizer' => '\OpenAPI\Client\Model\AdGroupServiceManualConversionOptimizer',
        'none_conversion_optimizer' => '\OpenAPI\Client\Model\AdGroupServiceNoneConversionOptimizer',
        'optimizer_type' => '\OpenAPI\Client\Model\AdGroupServiceOptimizerType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'auto_conversion_optimizer' => null,
        'manual_conversion_optimizer' => null,
        'none_conversion_optimizer' => null,
        'optimizer_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'auto_conversion_optimizer' => 'autoConversionOptimizer',
        'manual_conversion_optimizer' => 'manualConversionOptimizer',
        'none_conversion_optimizer' => 'noneConversionOptimizer',
        'optimizer_type' => 'optimizerType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'auto_conversion_optimizer' => 'setAutoConversionOptimizer',
        'manual_conversion_optimizer' => 'setManualConversionOptimizer',
        'none_conversion_optimizer' => 'setNoneConversionOptimizer',
        'optimizer_type' => 'setOptimizerType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'auto_conversion_optimizer' => 'getAutoConversionOptimizer',
        'manual_conversion_optimizer' => 'getManualConversionOptimizer',
        'none_conversion_optimizer' => 'getNoneConversionOptimizer',
        'optimizer_type' => 'getOptimizerType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['auto_conversion_optimizer'] = isset($data['auto_conversion_optimizer']) ? $data['auto_conversion_optimizer'] : null;
        $this->container['manual_conversion_optimizer'] = isset($data['manual_conversion_optimizer']) ? $data['manual_conversion_optimizer'] : null;
        $this->container['none_conversion_optimizer'] = isset($data['none_conversion_optimizer']) ? $data['none_conversion_optimizer'] : null;
        $this->container['optimizer_type'] = isset($data['optimizer_type']) ? $data['optimizer_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets auto_conversion_optimizer
     *
     * @return \OpenAPI\Client\Model\AdGroupServiceAutoConversionOptimizer|null
     */
    public function getAutoConversionOptimizer()
    {
        return $this->container['auto_conversion_optimizer'];
    }

    /**
     * Sets auto_conversion_optimizer
     *
     * @param \OpenAPI\Client\Model\AdGroupServiceAutoConversionOptimizer|null $auto_conversion_optimizer auto_conversion_optimizer
     *
     * @return $this
     */
    public function setAutoConversionOptimizer($auto_conversion_optimizer)
    {
        $this->container['auto_conversion_optimizer'] = $auto_conversion_optimizer;

        return $this;
    }

    /**
     * Gets manual_conversion_optimizer
     *
     * @return \OpenAPI\Client\Model\AdGroupServiceManualConversionOptimizer|null
     */
    public function getManualConversionOptimizer()
    {
        return $this->container['manual_conversion_optimizer'];
    }

    /**
     * Sets manual_conversion_optimizer
     *
     * @param \OpenAPI\Client\Model\AdGroupServiceManualConversionOptimizer|null $manual_conversion_optimizer manual_conversion_optimizer
     *
     * @return $this
     */
    public function setManualConversionOptimizer($manual_conversion_optimizer)
    {
        $this->container['manual_conversion_optimizer'] = $manual_conversion_optimizer;

        return $this;
    }

    /**
     * Gets none_conversion_optimizer
     *
     * @return \OpenAPI\Client\Model\AdGroupServiceNoneConversionOptimizer|null
     */
    public function getNoneConversionOptimizer()
    {
        return $this->container['none_conversion_optimizer'];
    }

    /**
     * Sets none_conversion_optimizer
     *
     * @param \OpenAPI\Client\Model\AdGroupServiceNoneConversionOptimizer|null $none_conversion_optimizer none_conversion_optimizer
     *
     * @return $this
     */
    public function setNoneConversionOptimizer($none_conversion_optimizer)
    {
        $this->container['none_conversion_optimizer'] = $none_conversion_optimizer;

        return $this;
    }

    /**
     * Gets optimizer_type
     *
     * @return \OpenAPI\Client\Model\AdGroupServiceOptimizerType|null
     */
    public function getOptimizerType()
    {
        return $this->container['optimizer_type'];
    }

    /**
     * Sets optimizer_type
     *
     * @param \OpenAPI\Client\Model\AdGroupServiceOptimizerType|null $optimizer_type optimizer_type
     *
     * @return $this
     */
    public function setOptimizerType($optimizer_type)
    {
        $this->container['optimizer_type'] = $optimizer_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


