<?php
/**
 * FeedServiceControlType
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FeedServiceControlType Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;FeedServiceControlTypeは、制御タイプを表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;FeedServiceControlType serves control type.&lt;/div&gt; &lt;hr&gt; &lt;p&gt;* &lt;code&gt;UPLOAD_COUNT_LIMIT&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;アップロード回数上限&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Upload limit.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;FILE_ROWS_LIMIT&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;ファイル行数上限&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;File line limit.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;FILE_SIZE_LIMIT_COMPRESS&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;ファイルサイズ上限(圧縮)&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;File size limit (compressed).&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;FILE_SIZE_LIMIT_UNCOMPRESS&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;ファイルサイズ上限(非圧縮)&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;File size limit (uncompressed).&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;UNKNOWN&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;未知の値です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Unknown Value&lt;/span&gt;&lt;/p&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FeedServiceControlType
{
    /**
     * Possible values of this enum
     */
    const UPLOAD_COUNT_LIMIT = 'UPLOAD_COUNT_LIMIT';
    const FILE_ROWS_LIMIT = 'FILE_ROWS_LIMIT';
    const FILE_SIZE_LIMIT_COMPRESS = 'FILE_SIZE_LIMIT_COMPRESS';
    const FILE_SIZE_LIMIT_UNCOMPRESS = 'FILE_SIZE_LIMIT_UNCOMPRESS';
    const UNKNOWN = 'UNKNOWN';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UPLOAD_COUNT_LIMIT,
            self::FILE_ROWS_LIMIT,
            self::FILE_SIZE_LIMIT_COMPRESS,
            self::FILE_SIZE_LIMIT_UNCOMPRESS,
            self::UNKNOWN,
        ];
    }
}


