<?php
/**
 * MediaServiceFileType
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MediaServiceFileType Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt; MediaServiceFileTypeは、画像のファイルタイプです。&lt;br&gt; このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; MediaServiceFileType serves the file type of media.&lt;br&gt; Although this field will be returned in the response, it will be ignored on input. &lt;/div&gt; &lt;hr&gt; &lt;p&gt;* &lt;code&gt;GIF&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;GIF（静止画）です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;GIF image.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;PNG&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;PNGです。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;PNG image.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;JPEG&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;JPEGです。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;JPEG image.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;UNKNOWN&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;未知の値です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Unknown Value&lt;/span&gt;&lt;/p&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediaServiceFileType
{
    /**
     * Possible values of this enum
     */
    const JPEG = 'JPEG';
    const GIF = 'GIF';
    const PNG = 'PNG';
    const UNKNOWN = 'UNKNOWN';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::JPEG,
            self::GIF,
            self::PNG,
            self::UNKNOWN,
        ];
    }
}


