<?php
/**
 * RetargetingListServiceTargetListType
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RetargetingListServiceTargetListType Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt; RetargetingListServiceTargetListTypeは、ターゲティングの種別を表します。&lt;br&gt; このフィールドは、ADDおよびSET時に必須となります。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; RetargetingListServiceTargetListType serves types of targets. &lt;br&gt; This field is required in ADD and SET operation. &lt;/div&gt; &lt;hr&gt; &lt;p&gt;* &lt;code&gt;DEFAULT_LIST&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;デフォルトリストです。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Default List.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;RULE&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;ルール(条件)です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Rules (conditions).&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;COMBINATION&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;組み合わせです。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Combination.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;SIMILARITY&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;類似ユーザーリストです。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Similar User List.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;CUSTOM_AUDIENCE&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;カスタムオーディエンスリストです。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Custom Audience List.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;UNKNOWN&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;未知の値です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Unknown Value&lt;/span&gt;&lt;/p&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RetargetingListServiceTargetListType
{
    /**
     * Possible values of this enum
     */
    const DEFAULT_LIST = 'DEFAULT_LIST';
    const RULE = 'RULE';
    const COMBINATION = 'COMBINATION';
    const SIMILARITY = 'SIMILARITY';
    const CUSTOM_AUDIENCE = 'CUSTOM_AUDIENCE';
    const UNKNOWN = 'UNKNOWN';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DEFAULT_LIST,
            self::RULE,
            self::COMBINATION,
            self::SIMILARITY,
            self::CUSTOM_AUDIENCE,
            self::UNKNOWN,
        ];
    }
}


