<?php
/**
 * SearchKeywordIdeaServiceSortField
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SearchKeywordIdeaServiceSortField Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;SearchKeywordIdeaServiceSortFieldオブジェクトは、ソート対象項目です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;SearchKeywordIdeaServiceSortField object is sorting item.&lt;/div&gt; &lt;hr&gt; &lt;p&gt;* &lt;code&gt;KEYWORD&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;キーワード&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Keyword&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;KEYWORD_ID&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;キーワードID&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Keyword ID&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;DESKTOP_SEARCH_VOLUME&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;PCのリーチ数&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Reach Number of PC&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;SMART_PHONE_SEARCH_VOLUME&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;スマホのリーチ数&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Reach Number of smart phone&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;TABLET_SEARCH_VOLUME&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;タブレットのリーチ数&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Reach Number of tablet&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;RELEASE_DATE&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;キーワード追加日&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Date for keyword&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;UNKNOWN&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;未知の値です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Unknown Value&lt;/span&gt;&lt;/p&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchKeywordIdeaServiceSortField
{
    /**
     * Possible values of this enum
     */
    const KEYWORD = 'KEYWORD';
    const KEYWORD_ID = 'KEYWORD_ID';
    const DESKTOP_SEARCH_VOLUME = 'DESKTOP_SEARCH_VOLUME';
    const SMART_PHONE_SEARCH_VOLUME = 'SMART_PHONE_SEARCH_VOLUME';
    const TABLET_SEARCH_VOLUME = 'TABLET_SEARCH_VOLUME';
    const RELEASE_DATE = 'RELEASE_DATE';
    const UNKNOWN = 'UNKNOWN';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::KEYWORD,
            self::KEYWORD_ID,
            self::DESKTOP_SEARCH_VOLUME,
            self::SMART_PHONE_SEARCH_VOLUME,
            self::TABLET_SEARCH_VOLUME,
            self::RELEASE_DATE,
            self::UNKNOWN,
        ];
    }
}


