<?php
/**
 * StatsServiceType
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。<br> 「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br> https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.htmlを登録してください。 </div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! Ads API.<br> When you use \"Try it out\", you need to register your application in advance.<br> As one of redirect URI for application, you need to set \"https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.html\". </div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * StatsServiceType Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;StatsServiceTypeは、統計情報の種別を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;StatsServiceType displays the stats information type.&lt;/div&gt; &lt;hr&gt; &lt;p&gt;* &lt;code&gt;CAMPAIGN&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;キャンペーンの統計情報です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Campaign stats information.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;ADGROUP&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;広告グループの統計情報です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Ad group stats information.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;AD&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;広告の統計情報です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Ad stats information.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;IMAGE&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;画像の統計情報です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Image stats information.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;VIDEO&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;動画の統計情報です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Video stats information.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;TARGET&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;ターゲティングの統計情報です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Targeting stats information.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;* &lt;code&gt;UNKNOWN&lt;/code&gt; - &lt;span lang&#x3D;\&quot;ja\&quot;&gt;未知の値です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Unknown Value&lt;/span&gt;&lt;/p&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatsServiceType
{
    /**
     * Possible values of this enum
     */
    const CAMPAIGN = 'CAMPAIGN';
    const ADGROUP = 'ADGROUP';
    const AD = 'AD';
    const IMAGE = 'IMAGE';
    const VIDEO = 'VIDEO';
    const TARGET = 'TARGET';
    const UNKNOWN = 'UNKNOWN';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CAMPAIGN,
            self::ADGROUP,
            self::AD,
            self::IMAGE,
            self::VIDEO,
            self::TARGET,
            self::UNKNOWN,
        ];
    }
}


